# This

dns:
  image: leftstache/discovery:latest
#  image: xahrepap/dns:latest
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  cap_add:
    - NET_ADMIN
  environment:
    DNS_USE_UPSTREAM: "true"
    ZOOKEEPER_CONNECTION_STRING: "cluster_zookeeper_1.cluster:2181"
  ports:
    - "172.19.0.1:53:53/udp"

zookeeper:
  image: mesoscloud/zookeeper
  environment:
    MYID: 1